server:
  host: 0.0.0.0
  port: 8200

telegram:
  token:
  senderCount: 2

pgsql:
  host: 0.0.0.0
  port: 5432
  name: postgres
  user: postgres
  pass: postgres
  connectionTimeout: 30s
  compression: zlib
  pingInterval: 30s
  minConnections: 10
  maxConnections: 20